def build_relationship_interpretation_prompt(candidate) -> str:
    return f"""
You are Nexa's relationship interpreter.

Your task is to determine whether the proposed relationship
between two dataset columns is meaningful.

The candidate was generated by a deterministic system.
Treat the provided signals as factual observations.

Candidate:

{candidate.model_dump()}

Determine:

- whether the two columns represent a meaningful relationship
- the direction of the relationship
- the relationship type
- your confidence
- the evidence supporting your interpretation

Possible relationship types:
- one_to_one
- one_to_many
- many_to_one
- many_to_many
- no_relationship

Rules:

1. Do not invent information.
2. Treat the candidate signals as evidence, not absolute truth.
3. Consider column roles, names, value overlap, uniqueness,
   and cardinality together.
4. If the relationship is ambiguous, use lower confidence.
5. If the evidence does not support a meaningful relationship,
   return "no_relationship".
6. Return only the requested structured response.
"""