"""
End-to-end test for the NEXA query pipeline.

Run from the project root:

    python -m tests.test_pipeline

This test creates a controlled semantic environment and verifies:

    Natural-language query
        ↓
    Semantic Resolution
        ↓
    Query Planning
        ↓
    Join Planning
        ↓
    Execution Planning
        ↓
    SQL Generation
        ↓
    SQL Validation
        ↓
    Final SQL

The SQL is NOT executed against a database.
"""

from src.llm.schemas.registry import (
    ApprovalStatus,
    ColumnRegistryEntry,
    DatasetRegistryEntry,
    RelationshipRegistryEntry,
    SemanticRegistry,
)

from src.data.semantic.catalog.catalog import build_semantic_catalog

from src.query.pipeline import run_query


# =============================================================
# Controlled Test Registry
# =============================================================

def create_test_registry() -> SemanticRegistry:
    """
    Create a small approved semantic registry for testing
    the NEXA query pipeline.

    This intentionally skips:

        - profiling
        - semantic interpretation
        - approval workflow
        - database loading

    The pipeline receives the semantic environment
    it expects directly.
    """

    # ---------------------------------------------------------
    # Customers
    # ---------------------------------------------------------

    customer_id = ColumnRegistryEntry(
        semantic_id="sem_customer_id",
        source_column="customer_id",
        suggested_meaning="customer identifier",
        suggested_description="Unique identifier for a customer.",
        suggested_role="identifier",
        confidence=0.99,
        evidence=[
            "Column name is customer_id"
        ],
        approved_meaning="customer identifier",
        approved_description="Unique identifier for a customer.",
        approved_role="identifier",
        approval_status=ApprovalStatus.APPROVED,
    )

    country = ColumnRegistryEntry(
        semantic_id="sem_country",
        source_column="country",
        suggested_meaning="customer country",
        suggested_description="Country associated with the customer.",
        suggested_role="dimension",
        confidence=0.98,
        evidence=[
            "Column contains country values"
        ],
        approved_meaning="customer country",
        approved_description="Country associated with the customer.",
        approved_role="dimension",
        approval_status=ApprovalStatus.APPROVED,
    )

    customers = DatasetRegistryEntry(
        dataset_name="customers",
        suggested_name="Customers",
        suggested_description="Customer records.",
        confidence=0.99,
        approved_name="Customers",
        approved_description="Customer records.",
        approval_status=ApprovalStatus.APPROVED,
        columns=[
            customer_id,
            country,
        ],
    )

    # ---------------------------------------------------------
    # Transactions
    # ---------------------------------------------------------

    transaction_customer_id = ColumnRegistryEntry(
        semantic_id="sem_transaction_customer_id",
        source_column="customer_id",
        suggested_meaning="transaction customer identifier",
        suggested_description=(
            "Customer identifier associated with a transaction."
        ),
        suggested_role="foreign_key",
        confidence=0.99,
        evidence=[
            "Column name matches customers.customer_id"
        ],
        approved_meaning="transaction customer identifier",
        approved_description=(
            "Customer identifier associated with a transaction."
        ),
        approved_role="foreign_key",
        approval_status=ApprovalStatus.APPROVED,
    )

    revenue = ColumnRegistryEntry(
        semantic_id="sem_revenue",
        source_column="revenue",
        suggested_meaning="revenue",
        suggested_description="Revenue generated by a transaction.",
        suggested_role="metric",
        confidence=0.99,
        evidence=[
            "Column represents monetary transaction value"
        ],
        approved_meaning="revenue",
        approved_description="Revenue generated by a transaction.",
        approved_role="metric",
        approval_status=ApprovalStatus.APPROVED,
    )

    transaction_date = ColumnRegistryEntry(
        semantic_id="sem_transaction_date",
        source_column="date",
        suggested_meaning="transaction date",
        suggested_description="Date on which the transaction occurred.",
        suggested_role="time",
        confidence=0.98,
        evidence=[
            "Column contains transaction dates"
        ],
        approved_meaning="transaction date",
        approved_description="Date on which the transaction occurred.",
        approved_role="time",
        approval_status=ApprovalStatus.APPROVED,
    )

    transactions = DatasetRegistryEntry(
        dataset_name="transactions",
        suggested_name="Transactions",
        suggested_description="Transaction records.",
        confidence=0.99,
        approved_name="Transactions",
        approved_description="Transaction records.",
        approval_status=ApprovalStatus.APPROVED,
        columns=[
            transaction_customer_id,
            revenue,
            transaction_date,
        ],
    )

    # ---------------------------------------------------------
    # Relationship
    # ---------------------------------------------------------

    customer_transaction_relationship = RelationshipRegistryEntry(
        source_dataset="customers",
        source_column="customer_id",
        target_dataset="transactions",
        target_column="customer_id",
        relationship_type="one-to-many",
        confidence=0.99,
        evidence=[
            "customers.customer_id matches transactions.customer_id",
            "One customer can have multiple transactions",
        ],
        approval_status=ApprovalStatus.APPROVED,
    )

    # ---------------------------------------------------------
    # Registry
    # ---------------------------------------------------------

    return SemanticRegistry(
        datasets=[
            customers,
            transactions,
        ],
        relationships=[
            customer_transaction_relationship,
        ],
    )


# =============================================================
# Main Pipeline Test
# =============================================================

def main():

    # ---------------------------------------------------------
    # 1. Create controlled test environment
    # ---------------------------------------------------------

    registry = create_test_registry()

    print("\n" + "=" * 60)
    print("TEST REGISTRY")
    print("=" * 60)

    print(f"Datasets: {len(registry.datasets)}")
    print(f"Relationships: {len(registry.relationships)}")

    assert len(registry.datasets) == 2
    assert len(registry.relationships) == 1

    # ---------------------------------------------------------
    # 2. Build semantic catalog
    # ---------------------------------------------------------

    catalog = build_semantic_catalog(registry)

    print("\n" + "=" * 60)
    print("SEMANTIC CATALOG")
    print("=" * 60)

    print(f"Catalog entries: {len(catalog)}")

    for entry in catalog:
        print(
            f"  {entry.semantic_id}"
            f" | {entry.approved_meaning}"
        )

    # We expect the approved semantic columns
    # to appear in the catalog.
    assert len(catalog) > 0

    # ---------------------------------------------------------
    # 3. Database schema
    # ---------------------------------------------------------

    database_schema = """
customers:
    customer_id
    country

transactions:
    customer_id
    revenue
    date
"""

    # ---------------------------------------------------------
    # 4. User query
    # ---------------------------------------------------------

    query = "Show the total revenue by country."

    print("\n" + "=" * 60)
    print("RUNNING NEXA PIPELINE")
    print("=" * 60)

    print(f"Query: {query}")

    # ---------------------------------------------------------
    # 5. Run complete pipeline
    # ---------------------------------------------------------

    sql = run_query(
        query=query,
        registry=registry,
        catalog=catalog,
        database_schema=database_schema,
    )

    # ---------------------------------------------------------
    # 6. Verify pipeline returned SQL
    # ---------------------------------------------------------

    assert isinstance(sql, str)
    assert sql.strip()

    # ---------------------------------------------------------
    # 7. Verify important SQL components
    # ---------------------------------------------------------

    normalized_sql = " ".join(sql.lower().split())

    assert "select" in normalized_sql
    assert "customers" in normalized_sql
    assert "transactions" in normalized_sql
    assert "country" in normalized_sql
    assert "revenue" in normalized_sql
    assert "sum" in normalized_sql

    # ---------------------------------------------------------
    # 8. Display generated SQL
    # ---------------------------------------------------------

    print("\n" + "=" * 60)
    print("GENERATED SQL")
    print("=" * 60)

    print(sql)

    # ---------------------------------------------------------
    # 9. Pipeline validation confirmation
    # ---------------------------------------------------------

    print("\n" + "=" * 60)
    print("VALIDATION")
    print("=" * 60)

    print("PASS: SQL returned successfully.")
    print("PASS: SQL contains expected tables.")
    print("PASS: SQL contains expected dimension.")
    print("PASS: SQL contains expected metric.")
    print("PASS: SQL contains SUM aggregation.")
    print("PASS: SQL passed the SQL validation layer.")

    # ---------------------------------------------------------
    # 10. Complete
    # ---------------------------------------------------------

    print("\n" + "=" * 60)
    print("PIPELINE COMPLETE")
    print("=" * 60)

    print("PASS: NEXA end-to-end pipeline test passed.")


# =============================================================
# Entry Point
# =============================================================

if __name__ == "__main__":
    main()