from src.data.database.repositories.registry import (
    save_registry,
    load_registry,
)

from src.llm.schemas.registry import (
    ApprovalStatus,
    ColumnRegistryEntry,
    DatasetRegistryEntry,
    RelationshipRegistryEntry,
    SemanticRegistry,
)


def create_approved_registry() -> SemanticRegistry:

    # =========================================================
    # Customers
    # =========================================================

    customer_id = ColumnRegistryEntry(
        semantic_id="sem_customer_id",
        source_column="customer_id",
        suggested_meaning="customer identifier",
        suggested_description="Unique identifier for a customer.",
        suggested_role="identifier",
        confidence=0.99,
        evidence=["Column name is customer_id"],
        approved_meaning="customer identifier",
        approved_description="Unique identifier for a customer.",
        approved_role="identifier",
        approval_status=ApprovalStatus.APPROVED,
    )

    country = ColumnRegistryEntry(
        semantic_id="sem_country",
        source_column="country",
        suggested_meaning="customer country",
        suggested_description="Country associated with the customer.",
        suggested_role="dimension",
        confidence=0.98,
        evidence=["Column represents customer country"],
        approved_meaning="customer country",
        approved_description="Country associated with the customer.",
        approved_role="dimension",
        approval_status=ApprovalStatus.APPROVED,
    )

    customers = DatasetRegistryEntry(
        dataset_name="customers",
        suggested_name="Customers",
        suggested_description="Customer records.",
        confidence=0.99,
        approved_name="Customers",
        approved_description="Customer records.",
        approval_status=ApprovalStatus.APPROVED,
        columns=[
            customer_id,
            country,
        ],
    )

    # =========================================================
    # Transactions
    # =========================================================

    transaction_customer_id = ColumnRegistryEntry(
        semantic_id="sem_transaction_customer_id",
        source_column="customer_id",
        suggested_meaning="transaction customer identifier",
        suggested_description=(
            "Customer identifier associated with a transaction."
        ),
        suggested_role="foreign_key",
        confidence=0.99,
        evidence=[
            "Column matches customers.customer_id"
        ],
        approved_meaning="transaction customer identifier",
        approved_description=(
            "Customer identifier associated with a transaction."
        ),
        approved_role="foreign_key",
        approval_status=ApprovalStatus.APPROVED,
    )

    revenue = ColumnRegistryEntry(
        semantic_id="sem_revenue",
        source_column="revenue",
        suggested_meaning="revenue",
        suggested_description="Revenue generated by a transaction.",
        suggested_role="metric",
        confidence=0.99,
        evidence=[
            "Column represents transaction revenue"
        ],
        approved_meaning="revenue",
        approved_description="Revenue generated by a transaction.",
        approved_role="metric",
        approval_status=ApprovalStatus.APPROVED,
    )

    transaction_date = ColumnRegistryEntry(
        semantic_id="sem_transaction_date",
        source_column="date",
        suggested_meaning="transaction date",
        suggested_description="Date of the transaction.",
        suggested_role="time",
        confidence=0.98,
        evidence=[
            "Column represents transaction dates"
        ],
        approved_meaning="transaction date",
        approved_description="Date of the transaction.",
        approved_role="time",
        approval_status=ApprovalStatus.APPROVED,
    )

    transactions = DatasetRegistryEntry(
        dataset_name="transactions",
        suggested_name="Transactions",
        suggested_description="Transaction records.",
        confidence=0.99,
        approved_name="Transactions",
        approved_description="Transaction records.",
        approval_status=ApprovalStatus.APPROVED,
        columns=[
            transaction_customer_id,
            revenue,
            transaction_date,
        ],
    )

    # =========================================================
    # Relationship
    # =========================================================

    customer_transaction_relationship = (
        RelationshipRegistryEntry(
            source_dataset="customers",
            source_column="customer_id",
            target_dataset="transactions",
            target_column="customer_id",
            relationship_type="one-to-many",
            confidence=0.99,
            evidence=[
                "customers.customer_id matches "
                "transactions.customer_id",
                "One customer can have multiple transactions",
            ],
            approval_status=ApprovalStatus.APPROVED,
        )
    )

    # =========================================================
    # Registry
    # =========================================================

    return SemanticRegistry(
        datasets=[
            customers,
            transactions,
        ],
        relationships=[
            customer_transaction_relationship,
        ],
    )


def main():

    print("\n" + "=" * 60)
    print("CREATING APPROVED NEXA REGISTRY")
    print("=" * 60)

    registry = create_approved_registry()

    print(
        f"Datasets: {len(registry.datasets)}"
    )

    print(
        f"Relationships: {len(registry.relationships)}"
    )

    # ---------------------------------------------------------
    # Save
    # ---------------------------------------------------------

    print("\nSaving registry...")

    save_registry(registry)

    print("Registry saved.")

    # ---------------------------------------------------------
    # Load again
    # ---------------------------------------------------------

    print("\nLoading registry from database...")

    loaded_registry = load_registry()

    print(
        f"Loaded datasets: "
        f"{len(loaded_registry.datasets)}"
    )

    print(
        f"Loaded relationships: "
        f"{len(loaded_registry.relationships)}"
    )

    # ---------------------------------------------------------
    # Verify
    # ---------------------------------------------------------

    assert len(loaded_registry.datasets) == 2
    assert len(loaded_registry.relationships) == 1

    for dataset in loaded_registry.datasets:

        print(
            f"\nDataset: {dataset.dataset_name}"
        )

        print(
            f"Status: {dataset.approval_status}"
        )

        for column in dataset.columns:

            print(
                f"  {column.source_column}"
                f" | {column.approval_status}"
                f" | {column.approved_meaning}"
            )

            assert (
                column.approval_status
                == ApprovalStatus.APPROVED
            )

            assert column.approved_meaning is not None

    print("\n" + "=" * 60)
    print("REAL REGISTRY TEST PASSED")
    print("=" * 60)


if __name__ == "__main__":
    main()